### ISSUE TITLE
NameError: name 'NSNitro' is not defined

### ISSUE THREAD

**Issue by SimplySeth** [eBayClassifiedsGroup/nsnitro#89]
Noob Alert: 
1> Cloned the repo with git
2> Entered directory and did `sudo python setup.py install`
3> did `import nsnitro *`
4> did `nitro = NSNitro('TestedIP', 'TestedUsername', 'TestedPassword')`

Result:  

```
traceback (most recent call last):
  File "./lbtool_nitro.py", line 3, in <module>
    from nsnitro import *
  File "/home/sreinoso/scripts/nsnitro.py", line 5, in <module>
NameError: name 'NSNitro' is not defined
```

Thanks.

**Comment by deniszh** [comment]
Hi @SimplySeth ,

Please check https://github.com/favoretti/nsnitro/blob/master/bin/nsnitrocmd.py for examples.

``` python
>>> import nsnitro
>>> nitro = NSNitro('TestedIP', 'TestedUsername', 'TestedPassword')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'NSNitro' is not defined
>>> from nsnitro.nsnitro import *
>>> nitro = NSNitro('TestedIP', 'TestedUsername', 'TestedPassword')
>>>
```
